### ISSUE TITLE
disable console logging

### ISSUE THREAD

**Issue by ClementsWayne** [bserdar/jcliff#80]
I can do this via cli:
/subsystem=logging/console-handler=CONSOLE:disable

I would like to do this using jcliff. I tried th below and it is not working
cat jcliff_config/logging_console.conf { "logging" => { "console-handler" => { "CONSOLE" => "disable" } } } 

The only jcliff query working currently is for log level.
{ "logging" => { "console-handler" => { "CONSOLE" => "level" => "INFO" } } } 

Can you assist

**Comment by bserdar** [comment]
Jcliff finds the differences between the desired configuration and current configuration, then runs CLI scripts to bring the current configuration to the desired state. CONSOLE=>"disable" is invalid, because it is trying to set CONSOLE, which is an object, to a string "disable".

What you need to do is to set CONSOLE.enabled to false. Try this:

{ "logging" => { "console-handler" => { "CONSOLE" => {"enabled"=>false } } }

Let me know,

**Comment by bserdar** [comment]
Any update on this?

**Comment by ClementsWayne** [comment]
Hi.

Worked like a charm. Thank you for your assistance.

Wayne Clements
